[toolchain]

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
callee = "E99XSKNk4C1F7ZvkxwdswpNHqAqnTK4pMKc8TxMxBhDi"
caller = "BBzvzW6cFCPuyQwjyE4wUvHkUGw7vziU9ZCUti1rCqyB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
